### ISSUE TITLE
Issues when adding country reports to website

### ISSUE THREAD

**Issue by sitinurliza95** [Sinar/imap#8]
1. Adding organization type: unable to save after editing  
2. Extracting page as pdf  
3. Adding footnotes  
4. Adding table of contents  
5. Adding image in pages: remove in menu bar e.g. 

![image](https://user-images.githubusercontent.com/86417001/196134410-e9e674ac-9f61-4a4a-8303-03cadb42642d.png)

**Comment by kaerumy** [comment]
1. Update src for organization (actually all of them) `bin/develop`, restart instance and reinstall organization https://github.com/Sinar/sinar.organization/issues/6

**Comment by sitinurliza95** [comment]
Got this error while running buildout (as in here https://github.com/Sinar/sinar.indicators/issues/1#issuecomment-1280512400):

```
mr.developer: Cloned 'sinar.indicators' with git using branch 'main' from 'git@github.com:Sinar/sinar.indicators'.
mr.developer: git cloning of 'sinar.indicators' failed.
mr.developer: Could not create directory '/var/www/.ssh'.
mr.developer: Failed to add the host to the list of known hosts (/var/www/.ssh/known_hosts).
mr.developer: git@github.com: Permission denied (publickey).
mr.developer: fatal: Could not read from remote repository.
mr.developer: 
mr.developer: Please make sure you have the correct access rights
mr.developer: and the repository exists.
mr.developer: 
mr.developer: There have been errors, see messages above.
```

**Comment by kaerumy** [comment]
Fixed. For deployment to use deployment.cfg and for local dev to use base buildout.cfg as to not do ssh checkout for deployment.
